---
title: "Automated Data flags"
date: "October 21, 2015"
output: html_document
---
#SC_badLabVSField
The difference between Lab SC (90095) and field SC (00095) is greater than 10%

#30.01. 
pH lower than expected Every water-quality sample (environmental and QC) had its pH (p00400) checked for appropriate ranges.  If the pH value is less than 4.5, the sample is flagged for 30.01.

#30.02. pH higher than expected
Every water-quality sample (environmental and QC) had its pH (p00400) checked for appropriate ranges.  If the pH value is higher than 9, the sample is flagged for 30.02.

#30.03.  Dissolved Oxygen higher than expected
Every water-quality sample (environmental and QC) had its dissolved oxygen (p00300) checked for appropriate ranges.  If the D.O. value is higher than 25, the sample is flagged for 30.03.

#30.11.  Greater than max value in old data
New Environmental samples are compared to “old” environmental samples at the same site from water-year 1996 and later, for pesticides, nutrients, field parameters, and major ions.  When a parameter has 5 or more “old” values at the site, and a new sample has a new maximum for that parameter, that sample and parameter are flagged for 30.11.  Pesticides in Schedule 2437 which existed in the earlier schedules 2033 or 2060 (under different pcodes) are compared to the older pcodes as well as the Schedule 2437 pcodes.

#30.12.  Less than min value in old data
New Environmental samples are compared to “old” environmental samples at the same site from water-year 1996 and later, for pesticides, nutrients, field parameters, and major ions.  When a parameter has 5 or more “old” values at the site, and a new sample has a new minimum for that parameter, that sample and parameter are flagged for 30.12.  Pesticides in Schedule 2437 which existed in the earlier schedules 2033 or 2060 (under different pcodes) are compared to the older pcodes as well as the Schedule 2437 pcodes.

#30.13.  Schedule 2437 Pesticide hits greater than max hits in old data
The number of Schedule 2437 pesticide hits in new environmental samples is compared to 2437 pesticide hits in “old” environmental samples at the same site from water-year 2013 and later (the year Schedule 2437 began).  When a site has 5 or more “old” pesticide samples and a new sample has a new maximum number of pesticide hits, that sample is flagged for 30.13.  Only pesticides in Schedule 2437 are counted as hits.

#30.14 Less than minimum pesticide hits in old data
The number of Schedule 2437 pesticide hits in new environmental samples is compared to 2437 pesticide hits in “old” environmental samples at the same site from water-year 2013 and later (the year Schedule 2437 began).  When a site has five or more “old” pesticide samples and a new sample has a new minimum number of pesticide hits, that sample is flagged for 30.14.  Only pesticides in Schedule 2437 are counted as hits.

#30.15.  Greater than 99p in old data
New Environmental samples are compared to “old” environmental samples at the same site from water-year 1996 and later, for pesticides, nutrients, field parameters, and major ions.  When a parameter has 24 or more “old” values at the site, and a new sample has a value greater than the 99th percentile of the “old” data set for that parameter, that sample and parameter are flagged for 30.15.  Pesticides in Schedule 2437 which existed in the earlier schedules 2033 or 2060 (under different pcodes) are compared to the older pcodes as well as the Schedule 2437 pcodes.

#30.16.  Less than 1p in old data
New Environmental samples are compared to “old” environmental samples at the same site from water-year 1996 and later, for pesticides, nutrients, field parameters, and major ions.  When a parameter has 24 or more “old” values at the site, and a new sample has a value less than the 1st percentile of the “old” data set for that parameter, that sample and parameter are flagged for 30.15.  Pesticides in Schedule 2437 which existed in the earlier schedules 2033 or 2060 (under different pcodes) are compared to the older pcodes as well as the Schedule 2437 pcodes.

#30.21.  Questionable cation-anion balance
For each environmental sample, the cation-anion percent difference was be calculated (using the same formula, but a slightly simpler procedure, than what NWIS-QWDATA uses) and compared to the value for specific conductance (P00095).  The cation-anion ballance is flagged for 30.21 if any of the following conditions is true
1. specific conductance is less than or equal to 100 microsiemens/cm, AND percent difference is greater (in absolute value) than +/- 15 percent
2. specific conductance is greater than 100 and less than or equal to 1000 microsiemens/cm, AND percent difference is greater (in absolute value) than +/- 10 percent
3. specific conductance is greater than 1000 microsiemens/cm, AND percent difference is greater (in absolute value) than +/- 5 percent

