---
title: "WQReview GUI - working with interactive plots"
author: "T. Joe Mills"
date: "`r Sys.Date()`"
output:
  html_vignette:
    toc: true
    toc_depth: 4
            
vignette: >
  %\VignetteIndexEntry{WQReview GUI- working with interactive plots}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---


#Plot descriptions
This vignette will describe the plot types available in the WQReview GUI and the various ways to manipulate them.

##Symbology
The symbology in all plots is sensitive to the medium code and remark code. Data colors are mapped to the medium code and point data symbols are mapped to the remark code. 

Currently supported medium codes include:

1. WS
1. WG
1. OA
1. WSQ
1. WGQ
1. OAQ

Currently supported remark codes include:

1. No remark code (listed as "Sample" in legend)
1. <
1. '>'
1. E

##Labelling conventions
All axis pertaining to a particular pcode will be labelled with that pcode's NWIS parameter name, which includes the units of measurement. The main title of the plot will either by labelled with the NWIS station name if only one station is plotted, or "multi-site plot" if multiple stations are displayed.

##Selecting data to plot
Generally, plots are controlled by selecting a site and then a data type from an input box or pick list. In most cases the plot will be displayed or refreshed automatically. **PLOTS WILL NOT BE DISPLAYED IF A SITE AND DATA TYPE ARE NOT SELECTED EVEN IF ONLY ONE SITE OR DATA TYPE IS PRESENT**. Additionally, a plot will not be displayed if there are no data to plot, for example if a particular parameter was not measured at a selected site but is selected for plotting. Multiple sites of multiple parameters can be plotted on certain plot types.

##Global plot controls

###New data threshold
Point data in all plots can be labeled as "New" data based off of when that data was last modified using the "New data threshold" slider. Any data modified after the date indicated on the slider will be labeled as "New". This helps identify data that has not been reviewed from historic data when the data are not displayed as a timeseries. Note that the "New data threshold" is set off of when the data were last **modified** for result-level plots (e.g. timeseries, seasonal, etc.) not when they were created. Sample-level plots (e.g. charge balance) are labeled new according to the sample collection date.

###Record highlights
Samples or results will be hilighted with a red halo if that sample or result has been flagged for one or more of the data checks listed in the data check table.

###Plot clicking, brushing, and hovering
Most plots are interactive in that the user can click on a point, or zoom into specific areas of the plot. Boxplots are not interactive. 

####Clicking
Clicking on a datapoint will populate a table with all data pertaining to that point. This table will persist until another point is clicked. 

####Brushing
The user may also select and area of the plot by holding down a mouse click and drawing a rectangle around hte area of interest. A new plot will appear below, zoomed into the area of interest. Additionaly, a table will be displayed below with all data pertaining to the points within the zoomed area. Points in the zoomed plot can also be click to get information. 

####Hovering
Hovering the mouse over any given data point will display basic information about the data point on the left sidebar of the plot frame.

##Plot types

This section will describe the details of each different plot type and how to control them in the WQReview GUI.

###Timeseries

This tab generates of plot of a selected parameter through time. 

####Uses
* Identifying general trends at a site through time.
* Identifying temporal outliers.

####Data selection options

* Select one or multiple sites
* Select only one parameter

####Plot controls
* Multi-site options: Plot all sites on one plot (multisite) or plot sites on individual side-by-side plots (facet).
* Add LOESS: Adds a locally weighted scatterplot smooth and shaded 95% confidence interval around the smooth
* Display hydrograph: displays the instantaneous hydrograph if data are available under parameter code "00061"

###Seasonal plot
This pane generates a seasonal timeseries of parameter value by day of year (DOY) to examine seasonality in parameter values.

####Uses
* Identifying seasonality in parameter values.
* Identifying seasonal outliers.

####Data selection options

* Select one or multiple sites
* Select only one parameter

####Plot controls

* Multi-site options: Plot all sites on one plot (multisite) or plot sites on individual side-by-side plots (facet).
* Add LOESS: Adds a locally weighted scatterplot smooth and shaded 95% confidence interval around the smooth

###Parameter box plot
This pane generates a box plot of one or more parameters for one or more sites. **Note that this is not an appropriate censored boxplot. Censored results are given the censored value for quantile calculations.**

####Uses
* Comparing parameter values at a site(s).
* Identifying outliers in a parameter. 

####Data selection options

* Select one or multiple sites
* Select one or multiple parameters


####Plot controls
* Log 10 scale: This plots parameter values on a log10 scale.
* Show sample points: This displays individual sample points.
* Multi-site options: Plot all sites on one plot (multisite) or plot sites on individual side-by-side plots (facet).

###Parameter-parameter plot
This pane generates an x-y plot of a selected parameter vs another selected parameter. 

####Uses
* Identifying relationships between parameters.
* Identifying outliers in related parameters.

####Data selection options

* Select one or multiple sites
* Select only one parameter per axis

####Plot controls
* Multi-site options: Plot all sites on one plot (multisite) or plot sites on individual side-by-side plots (facet).
* Add linear fit: Add a linear regression line to the x-y data.
* Log 10 scale: This plots parameter values on a log10 scale.

###Matrix plot
This pane generates a plot matrix of one or more parameters for one or more sites. Essentially, this is a parameter-parameter plot for multiple parameters. The lower triangular quadrant of panels are parameter-parameter plots, the diagonal contains a histogram of values and the labelled pcodes, and the upper triangular quadrant of panels contains the correlation coefficients.

####Uses
* Data exploration.
* Site characterization.

####Data selection options

* Select one or multiple sites
* Select one or multiple parameters

####Plot controls

*None

###Chargebalance timeseries
This pane generates a timeseries plot of charge balance percent difference. The plot is annotated with a horizontal dashed line indicating the range of +- 5% and a solid line indicating the range of +- 10%. Symbol type indicates if enough major elements were analyzed to constitute a roughly complete balance. For example, a sample missing calcium would be given a symbol of "Incomplete" because it is a major constituent in the charge balance, but a sample missing fluoride would still be given a "Complete" symbol because it is only a minor constituent of the charge balance.  

####Uses
* Obtaining a quick visual snapshot of charge imbalance at a site.
* Identifying charge imbalance issues with current data and comparing to historic chargebalance behavior.

####Data selection options

* Select one or multiple sites

####Plot controls
* Multi-site options: Plot all sites on one plot (multisite) or plot sites on individual side-by-side plots (facet).

###Ions vs conductance
This pane generates a x-y plot of sum of cations or anions vs conductance. The ratio of the sum of cations or anions vs specific conductance generally falls within a range of 0.92 - 1.24 for natural waters. The shaded region on the plot indicates this typical range. These are the values used in QWData for alert limits, see QWData documentation and references therein for further explanation. 

At many sites, there will be a roughly linear relationship between the sum of cations or anions vs. conductance. If a point falls above or below the general trend line, this is an indication that the particular group of ions is either to low or too high.

####Uses
* Identifying samples that fall outside of the typical range of rations of ions/specific conductance.
* Identifying which group of ions, cations or anions, are responsible for charge imbalance issues. 

####Data selection options

* Select one or multiple sites

####Plot controls

* Multi-site options: Plot all sites on one plot (multisite) or plot sites on individual side-by-side plots (facet).


###Rep-parm boxplot
This pane generates a plot of replicate relative percent difference for all replicates analyzed at a given site. **READ THE FOLLOWING ON REPLICATE PAIRING**

Replicate pairs are identified as follows:

1. An environmental sample is a sample with medium code of WS or WG and a sample type of 7.
1. A replicate sample is a sample with a medium code of WSQ or WGQ and a sample type of 7.
1. An environmental-replicate pair is defined as a replicate sample collected at the same site as an environmental sample on the same day. 

**NOTE THAT CENSORED RESULTS ARE GIVEN THE CENSORED VALUE FOR CALCULATIONS. DO NOT INTERPRET REPLICATE ANALYSES BASED ENTIRELY OFF OF THE RELATIVE PERCENT DIFFERENCE PLOT. SEE REPLICATE TABLE AS WELL.**

Boxplots can be grouped by time frame to compare current replicate agreement to historic using the "New replicate threshold" data input at the top of the page. This functions exactly the same as the "New data threshold" described in the Global Controls section of this vignette.

####Uses
* Assessing general replicate agreement at a site for multiple parameters.
* Comparing current replicate analyses to historic agreement. 

####Data selection options

* Select one or multiple sites
* Select one or multiple parameters

####Plot controls

* New replicate threshold: Sets the date break for historic vs new replicate analyses.
* Show sample points: This displays individual sample points.

###Blank sample timeseries
This pane generates a plot of parameter values for blank samples over time. 

####Uses
* Identifying systematic detections in blank samples at a given time, for example during a change in field or laboratory method or reporting level.

####Data selection options

* Select one or multiple sites
* Select only one parameter

####Plot controls

* Multi-site options: Plot all sites on one plot (multisite) or plot sites on individual side-by-side plots (facet).
